import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search, Globe, TrendingUp, BookOpen, Lightbulb, Atom } from "lucide-react";
import AdBanner from "@/components/AdBanner";
import WikiHeader from "@/components/WikiHeader";

const trendingTopics = [
  { name: "Artificial Intelligence", icon: Lightbulb },
  { name: "Quantum Computing", icon: Atom },
  { name: "Climate Change", icon: Globe },
  { name: "Space Exploration", icon: TrendingUp },
  { name: "Blockchain Technology", icon: BookOpen },
  { name: "Renewable Energy", icon: Lightbulb },
];

const Index = () => {
  const [query, setQuery] = useState("");
  const navigate = useNavigate();

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (query.trim()) {
      navigate(`/article/${encodeURIComponent(query.trim())}`);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <WikiHeader />

      {/* Top section: Hero + Search */}
      <div className="wiki-container pt-8 pb-4">
        <div className="text-center max-w-2xl mx-auto mb-6">
          <Globe className="h-14 w-14 text-primary mx-auto mb-3" />
          <h1 className="font-heading text-4xl md:text-5xl font-bold text-foreground mb-2">
            KnowHub
          </h1>
          <p className="font-body text-lg text-muted-foreground">
            The AI-powered encyclopedia. Search any topic and get comprehensive knowledge instantly.
          </p>
        </div>

        <form onSubmit={handleSearch} className="max-w-xl mx-auto">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search for any topic..."
              className="w-full rounded-full border-2 border-input bg-card px-12 py-3.5 text-base font-body focus:outline-none focus:ring-2 focus:ring-ring focus:border-primary transition-all"
            />
            <button
              type="submit"
              className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full bg-primary text-primary-foreground px-5 py-2 text-sm font-body font-semibold hover:opacity-90 transition-opacity"
            >
              Search
            </button>
          </div>
        </form>
      </div>

      {/* ===== CENTRAL AD BLOCK ===== */}
      <div className="flex-1 flex items-center justify-center py-6">
        <div className="w-full max-w-4xl mx-auto px-4">
          <AdBanner size="large" />
        </div>
      </div>

      {/* Bottom section: Trending Topics */}
      <div className="wiki-container pb-8">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-heading text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-accent" />
            Trending Topics
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {trendingTopics.map((topic) => {
              const Icon = topic.icon;
              return (
                <button
                  key={topic.name}
                  onClick={() => navigate(`/article/${encodeURIComponent(topic.name)}`)}
                  className="flex items-center gap-3 rounded-lg border border-border bg-card p-4 text-left hover:border-primary/50 hover:shadow-sm transition-all group"
                >
                  <Icon className="h-5 w-5 text-muted-foreground group-hover:text-primary transition-colors shrink-0" />
                  <span className="font-body text-sm font-medium text-foreground">{topic.name}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <footer className="border-t border-border py-6">
        <div className="wiki-container text-center text-sm text-muted-foreground font-body">
          <p>KnowHub — AI-Powered Knowledge. Content generated by artificial intelligence.</p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
